config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pets, only: [:show, :index, :new, :create] do
    resources :adoptions, only: [:create, :show]
  end

  resources :adoptions, only: [:index]

  resources :owners, only: [:new, :create]
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :pets, dependent: :destroy
  has_many :adoptions, through: :pets
  belongs_to :user
  mount_uploader :photo, PhotoUploader
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner
  has_many :adoptions, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # adoption chain for ownership
  has_one :owner, dependent: :destroy
  has_many :pets, through: :owner

  # adoption for adopting
  has_many :adoptions
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  def index
    @adoptions = current_user.owner.adoptions
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @adoption = Adoption.new
    @adoption.pet = @pet
    @adoption.user = current_user
    if @adoption.save
      redirect_to pet_adoption_path(@pet, @adoption)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    if current_user.owner
      # skip this form
      redirect_to new_pet_path
    else
      @owner = Owner.new
      @owner.user = current_user
    end
  end

  def create
    @owner = Owner.new(owner_params)
    @owner.user = current_user

    if @owner.save
      redirect_to new_pet_path
    end
  end

  private

  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :bio, :address, :contact, :photo)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all

    if user_signed_in?
      # filtering pets that the current user owned
      @pets -= current_user.pets

      # filter pets that the current user adopted

      @pets = @pets.reject do |pet|        
        if pet.adoptions.count == 1
          pet.adoptions.first.user == current_user
        end
      end
    end
  end

  def show
    @adoption = @pet.adoptions.build
    @adoption.user = current_user
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.owner = current_user.owner
    if @pet.save
      redirect_to pet_path(@pet)
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Your pet was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :image_url, :description, :category, :age, :gender, :hdb_approve)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adoptions/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div class="card">
        <img src="https://res.cloudinary.com/drrxcbatq/image/upload/v1574865021/banner2.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Adoptions</h5>
          <p class="card-text">Your pet is getting a new home!</p>
        </div>
          <% if %>
            
          <% end %>
          
          <% @adoptions.each do |adoption| %>        
          <div class="notification">
            <%= image_tag adoption.pet.image_url, class: "avatar-large" %>
            <div class="notification-content">
              <p><small><%= adoption.created_at %></small></p>
              <p><strong><%= adoption.user.email %></strong> wants to adopt <strong><%= adoption.pet.name %></strong></p>
            </div>
            <div class="notification-actions">
            <%= link_to "Acknowledge", root_path %>
            </div>
          </div>
          <% end %>

      </div>
    </div>  
  </div>  
</div>

app/views/adoptions/show.html.erb
<div class="container">
  <div class="card text-center">
    <div class="card-header">
      Featured
    </div>
    <div class="card-body">
      <h5 class="card-title">CONGRATULATIONS</h5>
      <p class="card-text">Your adoption is successful!</p>
      <%= link_to "Go back", root_path, class: "btn btn btn-info" %>
    </div>
    <div class="card-footer text-muted">
      2 days ago
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/owners/create.html.erb
<h1>Owners#create</h1>
<p>Find me in app/views/owners/create.html.erb</p>

app/views/owners/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create an account for adoption</h1>

      <%= simple_form_for (@owner) do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :bio %>
        <%= f.input :address %>
        <%= f.input :contact%>
        <%= f.button :submit, class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/pets/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/drrxcbatq/image/upload/v1574865021/banner2.jpg);">
  <div class="container">
    <h1><strong>Adopt-a-pet at Pet Station</strong></h1>
    <p>Change your life. Save a pet today.</p>
  </div>
</div>

<!-- <div class="container d-flex flex-column">
  <h5>Explore by categories</h5>
  <div class="row d-flex justify-content-between align-items-center">
  <div class="cards text-center">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
      Dogs
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
      Cats
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
      Guinea Pigs, Hamster, Rabbits and Gerbils
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
    Turtles, Terrapins and Tortoises
    </div>

     <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
    Others
    </div>
  </div>
  </div>
</div> -->


<div class="container">
  <h5>Explore by pets</h5>
    <div class="row d-flex justify-content-center align-items-center text-center">
      <% @pets.each do |pet| %>
        <div class="card" style="width: 20rem;">
          <% if pet.image_url %>
          <%= image_tag pet.image_url, class: "card-img-top", width: "100", height: "200" %>
          <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= pet.name %></h5>
              <p><%= pet.age%><span>months old<scan>, <%= pet.gender %></p>
              <p class="card-text col-10 text-truncate"><%= pet.description %></p>
               <%= link_to "Learn more", pet_path(pet), class: "btn btn-info" %>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>



<div class="footer text-center">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    <p>Copyright © 2019 Pet Station. All rights reserved.</p>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Add a pet for adoption</h1>

      <%= simple_form_for (@pet) do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :description %>
        <%= f.input :category, collection: [ "Dogs", "Cats", "Guinea Pigs, Hamster, Rabbits and Gerbils", "Turtles, Terrapins and Tortoises", "Others" ] %>
        <%= f.input :age %>
        <%= f.input :gender, collection: [ "Male", "Female" ] %>
        <%= f.input :HDB_approved %>
        <%= f.button :submit, class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="card">
        <%= image_tag @pet.image_url, class: "card-img-top", width: "100", height: "200" %>
          <div class="card-body">
            <h3 class="card-title"><%= @pet.name %></h3>
            <p class="card-text"><%= @pet.description %></p>
          </div>
          
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Age: <%= @pet.age %></li>
            <li class="list-group-item">Gender: <%= @pet.gender %></li>
            <li class="list-group-item">HDB-approved: <% if @pet.HDB_approved? %>
              Yes
              <% else %>
              No
              <% end %></li>
          </ul>
          <%= simple_form_for ([@pet, @adoption]) do |f| %>
            <%= f.button :submit, "Adopt Me", class: 'btn btn-primary btn-block' %>
          <% end %>
      </div>
    </div>

    <div class="col-12 col-lg-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title"><%= @pet.owner.first_name.capitalize %><%= @pet.owner.last_name %></h3>
          <p class="card-text"><%= @pet.owner.bio %></p>
        </div>
        <div class="card-body">
          <a href="https://wa.me/6597295356" class="card-link">Message Me on WhatsApp</a>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/pets/update.html.erb
<h1>Pets#update</h1>
<p>Find me in app/views/pets/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= cl_image_tag "https://res.cloudinary.com/drrxcbatq/image/upload/v1574863376/logo.png" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar navbar-light bg-light">
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
      </form>
  </div>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      
        <li class="nav-item active">
          <%= link_to "Add-a-Pet", new_owner_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <% unless current_user.owner.nil?  %>
            <%= link_to adoptions_path, class: "btn btn-primary" do %>
              Notifications <span class="badge badge-info"><%= current_user.owner.adoptions.count %><% link_to adoptions_path %></span>
            <% end %>
          <% end %>
        </li>
        
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
        </li>
        
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>